import type { ParameterType } from "../../algorithm/initialScoreAlgo/initialScore";

export const InitialScoreBackGroundVerification: ParameterType[] = [
    {
        key: "aadharVerification",
        label: "Aadhaar Verification",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate’s Aadhaar been successfully verified?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "panVerification",
        label: "PAN Verification",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate’s PAN been verified for authenticity?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "passportVerification",
        label: "Passport Verification",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate’s passport been verified?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "voterIdVerification",
        label: "Voter ID Verification",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate’s voter ID been verified?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "drivingLicenseVerification",
        label: "Driving License Verification",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate’s driving license been verified?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "faceMatchVerification",
        label: "Face Match Verification",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate’s face been successfully matched with their ID documents?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "addressVerification",
        label: "Address Verification",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate’s residential address been verified?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "geotagLocationVerification",
        label: "Geotag / Location Verification",
        type: "number",
        severity: "high",
        behaviour: "positive",
        question: "Has the candidate’s current location been geotagged and verified?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "courtRecordVerificationApi",
        label: "Court Record Verification API",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate been screened for any court records using the verification API?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "policeFirRecordCheckApi",
        label: "Police/FIR Record Check API",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate’s police/FIR record been verified through the API?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "criminalRecordVerification",
        label: "Criminal Record Verification",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate cleared the criminal record verification?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "drugTest",
        label: "Drug Test",
        type: "number",
        severity: "high",
        behaviour: "positive",
        question: "Has the candidate passed the drug screening test?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "universityDegreeVerification",
        label: "University Degree Verification",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate’s university degree been verified?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "employmentHistoryVerification",
        label: "Employment History Verification",
        type: "number",
        severity: "critical",
        behaviour: "positive",
        question: "Has the candidate’s employment history been verified?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "payrollDataVerification",
        label: "Payroll Data Verification",
        type: "number",
        severity: "high",
        behaviour: "positive",
        question: "Has the candidate’s payroll data been verified with previous employers?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "bankAccountVerification",
        label: "Bank Account Verification",
        type: "number",
        severity: "high",
        behaviour: "positive",
        question: "Has the candidate’s bank account been verified for validity?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "cibilScoreCheck",
        label: "CIBIL Score Check",
        type: "number",
        severity: "moderate",
        behaviour: "positive",
        question: "Has the candidate’s CIBIL score been checked and verified?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
    {
        key: "digitalSignVerification",
        label: "Digital Sign Verification",
        type: "number",
        severity: "moderate",
        behaviour: "positive",
        question: "Has the candidate’s digital signature been verified?",
        validation: { allowed: [true, false] },
        belongsTo: "backGroundVerification",
    },
];
