import type { ParameterType } from "../../algorithm/initialScoreAlgo/initialScore";

export const InitialScorePositiveParameter: ParameterType[] = [
    {
        key: "designToolsKnowledge",
        label: "Design Tools Knowledge",
        type: "boolean",
        severity: "belowAverage",
        question: "Does the candidate have working knowledge of design tools (e.g., Figma, Canva, Photoshop, etc.)?",
        validation: { allowed: [true, false] },
        behaviour: "positive",
        belongsTo: "positive",
    },
    {
        key: "linkedinProfileStrength",
        label: "LinkedIn Profile Strength",
        type: "number",
        severity: "elite",
        question: "How strong is the candidate’s LinkedIn profile (e.g., complete information, endorsements, activity, connections)?",
        validation: { min: 0, max: 100 },
        behaviour: "positive",
        belongsTo: "positive",
    },
    {
        key: "workExperienceInMncs",
        label: "Work Experience in MNCs",
        type: "boolean",
        severity: "aboveModerate",
        question: "Has the candidate worked with multinational corporations (MNCs) or globally recognized companies?",
        validation: { allowed: [true, false] },
        behaviour: "positive",
        belongsTo: "positive",
    },
    {
        key: "languagesKnown",
        label: "Languages Known",
        type: "number",
        severity: "moderate",
        question: "How many languages (including native) does the candidate speak or write fluently?",
        validation: { min: 1, max: 10 },
        behaviour: "positive",
        belongsTo: "positive",
    },
    {
        key: "freelanceOrConsultingExperience",
        label: "Freelance or Consulting Experience",
        type: "boolean",
        severity: "high",
        question: "Has the candidate undertaken freelance or consulting projects in their domain?",
        validation: { allowed: [true, false] },
        behaviour: "positive",
        belongsTo: "positive",
    },
    {
        key: "researchPublications",
        label: "Research Publications",
        type: "boolean",
        severity: "elite",
        question: "Has the candidate published research papers, journals, or articles in recognized platforms?",
        validation: { allowed: [true, false] },
        behaviour: "positive",
        belongsTo: "positive",
    },
    {
        key: "extracurricularParticipation",
        label: "Extracurricular Participation",
        type: "boolean",
        severity: "low",
        question: "Has the candidate participated in extracurricular, volunteer, or cultural initiatives?",
        validation: { allowed: [true, false] },
        behaviour: "positive",
        belongsTo: "positive",
    },
    {
        key: "projectManagementTools",
        label: "Project Management Tools Knowledge",
        type: "boolean",
        severity: "veryLow",
        behaviour: "positive",
        question: "Is the candidate experienced in using project management tools (e.g., Jira, Asana, Trello, ClickUp, etc.)?",
        validation: { allowed: [true, false] },
        belongsTo: "positive",
    },
    {
        key: "linkedinProfileStrength",
        label: "LinkedIn Profile Strength",
        type: "boolean",
        severity: "moderate",
        behaviour: "positive",
        question: "How strong is the candidate’s LinkedIn profile (e.g., complete information, endorsements, activity, connections)?",
        validation: { min: 0, max: 100 },
        belongsTo: "positive",
    },
    {
        key: "workExperienceInMncs",
        label: "Work Experience in MNCs",
        type: "boolean",
        severity: "moderate",
        behaviour: "positive",
        question: "Has the candidate worked with multinational corporations (MNCs) or globally recognized companies?",
        validation: { allowed: [true, false] },
        belongsTo: "positive",
    },
    {
        key: "languagesKnown",
        label: "Languages Known",
        type: "number",
        severity: "moderate",
        behaviour: "positive",
        question: "How many languages (including native) does the candidate speak or write fluently?",
        validation: { min: 1, max: 10 },
        belongsTo: "positive",
    },
    {
        key: "freelanceOrConsultingExperience",
        label: "Freelance or Consulting Experience",
        type: "boolean",
        severity: "moderate",
        behaviour: "positive",
        question: "Has the candidate undertaken freelance or consulting projects in their domain?",
        validation: { allowed: [true, false] },
        belongsTo: "positive",
    },
    {
        key: "employeeOfTheMonthOrQuarter",
        label: "Employee of the Month or Quarter",
        type: "boolean",
        severity: "high",
        behaviour: "positive",
        question: "Has the candidate been recognized as Employee of the Month or Quarter?",
        validation: { allowed: [true, false] },
        belongsTo: "positive",
    },
    {
        key: "numberOfPromotions",
        label: "Number of Promotions",
        type: "number",
        severity: "elite",
        behaviour: "positive",
        question: "How many promotions has the candidate received during their tenure?",
        validation: { min: 0, max: 15 },
        belongsTo: "positive",
    },
    {
        key: "exceededPerformanceTargets",
        label: "Exceeded Performance Targets",
        type: "boolean",
        severity: "high",
        behaviour: "positive",
        question: "Has the candidate consistently exceeded performance or sales targets?",
        validation: { allowed: [true, false] },
        belongsTo: "positive",
    },
    {
        key: "disputeFreeRecord",
        label: "Dispute-Free Record",
        type: "boolean",
        severity: "veryHigh",
        behaviour: "positive",
        question: "Does the candidate have a dispute-free record with no conflicts or grievances?",
        validation: { allowed: [true, false] },
        belongsTo: "positive",
    },
    {
        key: "highPeerFeedbackScore",
        label: "High Peer Feedback Score",
        type: "boolean",
        severity: "veryHigh",
        behaviour: "positive",
        question: "Has the candidate received consistently high peer feedback ratings?",
        validation: { allowed: [true, false] },
        belongsTo: "positive",
    },
];
